import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

_tool_path = Path(__file__)
TOOL_PATH_STR = f"{_tool_path.parent.name}/{_tool_path.name}"
CONTENT_BASE_PATH = Path("content")
OUT_DIR_PATH = Path("src/.generated/resources/")

CONTENT_CUBEMAPS = CONTENT_BASE_PATH / "cubemaps/"
CONTENT_IMAGES = CONTENT_BASE_PATH / "images/"
CONTENT_MODELS = CONTENT_BASE_PATH / "models/"
CONTENT_SHADERS = CONTENT_BASE_PATH / "shaders/"

GEN_PACKAGE_NAME = "resources"
FORMATTER_PROGRAM_NAME = "odinfmt"


@dataclass
class ResourcePath:
    index_name: str
    location: str
    quoted: bool

    def __post_init__(self):
        self.index_name = to_ada_case(self.index_name)


def q(text: str) -> str:
    return '"' + text + '"'


def program_exists(program_name: str) -> bool:
    return shutil.which(program_name) is not None


def to_ada_case(text: str) -> str:
    if len(text) == 0:
        return text

    s = text.split("_")
    return "_".join(w.capitalize() for w in s)


def build_index(items: list[ResourcePath]) -> str:
    return ",\n".join([it.index_name for it in items])


def build_indexed_array(items: list[ResourcePath]) -> str:
    return ",\n".join(
        [
            f".{it.index_name} = {q(it.location) if it.quoted else it.location}"
            for it in items
        ]
    )


def generate(
    items: list[ResourcePath], name: str, indexed_type: str, extra_decls: str
) -> str:
    print(f"Generating '{name}' resources...")
    index_enum_name = f"{to_ada_case(name)}_Index"
    return f"""package {GEN_PACKAGE_NAME}

// This file has been generated by "{TOOL_PATH_STR}", do not edit

{extra_decls}

{index_enum_name} :: enum {{
    {build_index(items)}
}}

@(rodata)
{name.upper()}_LOCATION := [{index_enum_name}]{indexed_type} {{
    {build_indexed_array(items)}
}}
"""


def gen_models() -> str:
    models: list[ResourcePath] = []

    for entry in CONTENT_MODELS.iterdir():
        if entry.is_dir():
            models.append(ResourcePath(entry.name, entry.name, True))

    return generate(models, "models", "string", "")


def gen_cubemaps() -> str:
    cubemaps: list[ResourcePath] = []

    for entry in CONTENT_CUBEMAPS.iterdir():
        if entry.is_dir():
            cubemaps.append(ResourcePath(entry.name, entry.name, True))

    return generate(cubemaps, "cubemaps", "string", "")


def gen_textures() -> str:
    textures: list[ResourcePath] = []

    for entry in CONTENT_IMAGES.iterdir():
        # without a proper resource system this must be done manually
        match entry.stem:
            case "grass":
                location = f"{q(entry.name)}, true, true"
            case "transparent_window":
                location = f"name = {q(entry.name)}, transparent = true"
            case _:
                location = f"name = {q(entry.name)}"

        textures.append(ResourcePath(entry.stem, "{" + location + "}", False))

    extra_decls = """
        Texture_Resource_Params :: struct {
                name:        string,
                flip:        bool,
                transparent: bool,
        }
    """

    return generate(textures, "textures", "Texture_Resource_Params", extra_decls)


def gen_shaders() -> str:
    class ParsingError(Exception):
        def __init__(self, error: str, line_num: int, line: str):
            super().__init__("Shader program resource parsing error")

            self.line_num = line_num
            self.line_content = line.strip("\n")
            self.error = error

        def __str__(self):
            return f"\nLINE {self.line_num}: {self.line_content}\nERROR: {self.error}"

    def _get_res_path(base: Path, name: str) -> list[str]:
        shaders = []

        for entry in (base / name).iterdir():
            if entry.is_file():
                shaders.append(entry.stem)

        return shaders

    all_vs = _get_res_path(CONTENT_SHADERS, "vertex")
    all_fs = _get_res_path(CONTENT_SHADERS, "fragment")
    all_gs = _get_res_path(CONTENT_SHADERS, "geometry")

    programs: list[ResourcePath] = []
    with (CONTENT_SHADERS / "programs.txt").open() as f:
        for i, line in enumerate(f):
            s = [t.strip() for t in line.split(",")]
            if len(s) != 4:
                raise ParsingError(
                    f"Wrong number of colunms, expected {4}, got {len(s)}", i, line
                )

            name, vs, fs, gs = s

            if vs not in all_vs:
                raise ParsingError(f"Unknown vertex shader: '{vs}'", i, line)

            if fs not in all_fs:
                raise ParsingError(f"Unknown fragment shader: '{fs}'", i, line)

            if gs != "nil" and gs not in all_gs:
                raise ParsingError(f"Unknown geometrty shader: '{gs}'", i, line)

            location = f"{q(name)}, {q(vs)}, {q(fs)}, {q(gs) if gs != 'nil' else gs}"

            programs.append(
                ResourcePath(
                    name,
                    "{" + location + "}",
                    False,
                )
            )

    extra_decls = """
    Shader_Program_Code :: struct {
        name:          string,
        vertex_name:   string,
        fragment_name: string,
        geometry_name: Maybe(string),
    }
    """

    return generate(programs, "shaders_program", "Shader_Program_Code", extra_decls)


def write_resource_file(filename: str, file_contents: str, should_format: bool):
    OUT_DIR_PATH.mkdir(parents=True, exist_ok=True)
    resource_file_path = OUT_DIR_PATH / f"{filename}_res.odin"

    if should_format:
        try:
            result = subprocess.run(
                [FORMATTER_PROGRAM_NAME, "-stdin"],
                text=True,
                check=True,
                input=file_contents,
                capture_output=True,
            )
            file_contents = result.stdout
        except subprocess.CalledProcessError as ex:
            print(ex)
            print(
                f"It's likely that the generated file ('{resource_file_path}') contains syntax errors"
            )
            should_format = False

    print(f"writing{' formatted' if should_format else ''} file '{resource_file_path}'")
    with resource_file_path.open("w+") as f:
        f.write(file_contents)


if __name__ == "__main__":
    models = gen_models()
    textures = gen_textures()
    shaders = gen_shaders()
    cubemaps = gen_cubemaps()

    should_format = False
    if program_exists(FORMATTER_PROGRAM_NAME):
        should_format = True
    else:
        print(
            f"Formatted '{FORMATTER_PROGRAM_NAME}' not found in PATH, format manually"
        )

    write_resource_file("models", models, should_format)
    write_resource_file("textures", textures, should_format)
    write_resource_file("cubemaps", cubemaps, should_format)
    write_resource_file("shaders", shaders, should_format)
